
SELECT ?facet ?label (count (?concept)as ?concept_NR) {
  ?facet a gvp:Facet;
           gvp:prefLabelGVP/xl:literalForm ?label;
           skos:inScheme aat:.
           
  ?facet skos:member+ ?concept
}

GROUP BY ?facet ?label

