################################################################################################################

# author: ETH Zurich, gta digital, Matteo Lorenzini
# license: please refer to the license.txt file in our git repository (https://github.com/gtadigital/GeoWrapper) 

################################################################################################################




###################################################################################################################################################################################################

# Q1 PLACES AND RELATED LABELS 

####################################################################################################################################################################################################

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX gvp: <http://vocab.getty.edu/ontology#>

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT  ?concept ?label ?concept_label_en ?concept_label_de ?concept_label_it ?concept_label_fr ?concept_label_hu ?concept_label_ca ?concept_label_ru ?concept_label_es ?concept_label_ellatn

WHERE {?s  gvp:AdminPlaceConcept ?concept;
           rdfs:label ?label.
  SERVICE <http://vocab.getty.edu/sparql> {
       ?concept a gvp:AdminPlaceConcept.
        
      OPTIONAL {{ ?concept xl:prefLabel ?concept_labelEN.?concept_labelEN gvp:term ?concept_label_en.} FILTER langMatches(lang(?concept_label_en), "en").}
      OPTIONAL {{ ?concept xl:prefLabel ?concept_labelDE.?concept_labelDE gvp:term ?concept_label_de.} FILTER langMatches(lang(?concept_label_de), "de").}
      OPTIONAL {{ ?concept xl:prefLabel ?concept_labelIT.?concept_labelIT gvp:term ?concept_label_it.} FILTER langMatches(lang(?concept_label_it), "it").}
      OPTIONAL {{ ?concept xl:prefLabel ?concept_labelFR.?concept_labelFR gvp:term ?concept_label_fr.} FILTER langMatches(lang(?concept_label_fr), "fr").}
      OPTIONAL {{ ?concept xl:prefLabel ?concept_labelHU.?concept_labelHU gvp:term ?concept_label_hu.} FILTER langMatches(lang(?concept_label_hu), "hu").}
   		OPTIONAL {{ ?concept xl:prefLabel ?concept_labelCA.?concept_labelCA gvp:term ?concept_label_ca.} FILTER langMatches(lang(?concept_label_ca), "ca").}
   		OPTIONAL {{ ?concept xl:prefLabel ?concept_labelRU.?concept_labelRU gvp:term ?concept_label_ru.} FILTER langMatches(lang(?concept_label_ru), "ru").}
   		OPTIONAL {{ ?concept xl:prefLabel ?concept_labelES.?concept_labelES gvp:term ?concept_label_es.} FILTER langMatches(lang(?concept_label_es), "es").}
   		OPTIONAL {{ ?concept xl:prefLabel ?concept_labelELLATN.?concept_labelELLATN gvp:term ?concept_label_ellatn.} FILTER langMatches(lang(?concept_label_ellatn), "el-latn").}
   }
    
    
    
}

LIMIT 10



###################################################################################################################################################################################################

# Q2 PLACES WITH LAT/LONG AND RELATED LABELS 

####################################################################################################################################################################################################





PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX gvp: <http://vocab.getty.edu/ontology#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>


SELECT  ?concept ?label ?concept_label_en ?concept_label_de ?concept_label_it ?concept_label_fr ?concept_label_hu ?concept_label_ca ?concept_label_ru ?concept_label_es ?concept_label_ellatn ?lat ?long

WHERE {?s  gvp:AdminPlaceConcept ?concept;
           rdfs:label ?label.
  SERVICE <http://vocab.getty.edu/sparql> {
       ?concept a gvp:AdminPlaceConcept.
       ?concept foaf:focus [wgs:lat ?lat; wgs:long ?long].
        
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelEN.?concept_labelEN gvp:term ?concept_label_en.} FILTER langMatches(lang(?concept_label_en), "en").}
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelDE.?concept_labelDE gvp:term ?concept_label_de.} FILTER langMatches(lang(?concept_label_de), "de").}
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelIT.?concept_labelIT gvp:term ?concept_label_it.} FILTER langMatches(lang(?concept_label_it), "it").}
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelFR.?concept_labelFR gvp:term ?concept_label_fr.} FILTER langMatches(lang(?concept_label_fr), "fr").}
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelHU.?concept_labelHU gvp:term ?concept_label_hu.} FILTER langMatches(lang(?concept_label_hu), "hu").}
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelCA.?concept_labelCA gvp:term ?concept_label_ca.} FILTER langMatches(lang(?concept_label_ca), "ca").}
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelRU.?concept_labelRU gvp:term ?concept_label_ru.} FILTER langMatches(lang(?concept_label_ru), "ru").}
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelES.?concept_labelES gvp:term ?concept_label_es.} FILTER langMatches(lang(?concept_label_es), "es").}
        OPTIONAL {{ ?concept xl:prefLabel ?concept_labelELLATN.?concept_labelELLATN gvp:term ?concept_label_ellatn.} FILTER langMatches(lang(?concept_label_ellatn), "el-latn").}
   }
    
    
    
}

LIMIT 10


###################################################################################################################################################################################################

# Q3 PLACES AND RELATED LABELS NO FILTER 

####################################################################################################################################################################################################




PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX gvp: <http://vocab.getty.edu/ontology#>
PREFIX wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT  ?concept ?label (group_concat( ?concept_label;separator="|" ) as ?concept_labels) ?lat ?long

WHERE {?s  gvp:AdminPlaceConcept ?concept;
           rdfs:label ?label.
  SERVICE <http://vocab.getty.edu/sparql> {
       ?concept a gvp:AdminPlaceConcept;
                  xl:prefLabel ?label_term.
       ?label_term gvp:term ?concept_label.
    ?concept foaf:focus [wgs:lat ?lat; wgs:long ?long].
       
   
   }
    
    
    
}

GROUP BY ?concept ?label ?concept_labels ?lat ?long



